User profile#1
HibyteIntern/internal-betting-be pull request #15
Opened 2023-12-13 13:01 UTC by AvrAlexandra

2023-12-14 14:15 UTC, DrBaxR requested changes
Ignore the comments that I left on files that are not yours/that don't apply to your files.

2023-12-14 14:15 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/service/UserProfileService.kt
> +        var userProfile = userProfileRepository.findById(userId)
Here I would get rid of the `if` and do something like `return userProfileRepository.findById(userId).orElse(/*...*/)`

2023-12-14 14:15 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/service/WaspService.kt
> +            set("X-API-KEY", "a4c1098d-9fda-4b27-b268-62a066f0cddd")
Extract to configuration (let me know when you get to this and I'll give you more details)

2023-12-14 14:15 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/service/WaspService.kt
> +            "https://wasp.live.hibyte.ro/api/files",
Extract to config

2023-12-14 14:15 UTC, DrBaxR commented on src/main/resources/application.yml
> +    password: 210902
Revert this to initial value and try to not commit your passwords (let me know when you get to this and I'll show you a trick that helps with this)

2024-01-15 09:17 UTC, DrBaxR approved these changes

2024-01-15 13:34 UTC, ambragoanta approved these changes

2024-01-26 13:28 UTC, merged