Crud competitions#4
HibyteIntern/internal-betting-be pull request #16
Opened 2023-12-13 19:31 UTC by Serban681

2023-12-14 14:34 UTC, DrBaxR requested changes
Ignore the comments I left on files that are not yours/that don't apply to your files

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/controller/CompetitionController.kt
> +    fun getOneById(@PathVariable id: Long): CompetitionDto {
You can make this method one line of you get rid of the intermediary variable. Something like this:

```kotlin
competitionMapper.mapCompetitionToCompetitionDto(competitionService.getOne(id))
```

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/controller/CompetitionController.kt
> +    fun create(@RequestBody dto: CompetitionRequest): ResponseEntity<CompetitionDto> {
Make one line

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/controller/CompetitionController.kt
> +        return ResponseEntity(competitionMapper.mapCompetitionToCompetitionDto(competition), HttpStatus.OK)
For post return `HttpStatus.CREATED` on success

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/controller/CompetitionController.kt
> +        val newCompetition = competitionService.update(id, dto)
Make one line

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/dto/EventDTO.kt
> +    var eventId: Long? =null,
Do a `Ctrl+Alt+L` here to automatically format file

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/mapper/CompetitionMapper.kt
> +    fun getEventsFromIds(eventIDs: List<Long>): List<Event> = eventIDs.map { id -> eventRepository.findById(id).orElseThrow{ EntityNotFoundException("Event", id) } }.toList()
Split line like this:

```kotlin
fun getEventsFromIds(eventIDs: List<Long>): List<Event> = 
    eventIDs.map { 
        id -> eventRepository.findById(id).orElseThrow{ EntityNotFoundException("Event", id) } 
    }.toList()

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/mapper/CompetitionMapper.kt
> +    fun getUserProfilesFromIds(userIDs: List<Long>): Set<UserProfile> = userIDs.map { id -> userProfileRepository.findById(id).orElseThrow { EntityNotFoundException("User Profile", id) } }.toSet()
Same here

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/mapper/CompetitionMapper.kt
> +    fun mapCompetitionRequestToCompetition(competitionRequest: CompetitionRequest): Competition {
You can use one line function syntax

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/mapper/CompetitionMapper.kt
> +    fun mapCompetitionRequestToCompetition(competitionRequest: CompetitionRequest, initialCompetition: Competition): Competition {
One line method syntax

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/mapper/CompetitionMapper.kt
> +    fun mapCompetitionToCompetitionDto(competition: Competition): CompetitionDto {
One line method syntax

2023-12-14 14:34 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/service/BetService.kt
> +    fun get(betId: Long): Bet {
One line syntax

2023-12-14 14:34 UTC, DrBaxR commented on src/main/resources/application.yml
> +    password: 1234
Don't commit local database/any password, please change to what it was before (let me know when you get to this, I can show you a trick that helps with this)

2023-12-14 14:35 UTC, DrBaxR commented
Did you close PR #12, made the changes requested there and opened a new PR? If so, you don't need to do that, if you make the changes on the same branch and push on it, the PR will be automatically updated

2023-12-14 16:36 UTC, Serban681 commented
I had problems when I was trying to pull code made by others. So I decided to create another branch and a new PR.

2023-12-15 15:12 UTC, DrBaxR approved these changes

2023-12-18 11:53 UTC, DanceaRadu approved these changes
The creator of the Competition is not set properly, but I assume this will be changed later, once the UserProfile tasks are completed. Other than that, it seems fine.

2023-12-20 13:34 UTC, merged