Jwt service#19
HibyteIntern/internal-betting-be pull request #20
Opened 2024-01-15 09:39 UTC by DanceaRadu

Added a service for decoding JWT tokens. This service will provide the UserProfile and the user permissions associated with a keycloak id.
For the time being, the service considers every account a 'USER', but once we more clearly define the roles in keycloak, the service will return those roles as well.

2024-01-15 10:40 UTC, DrBaxR requested changes
Looks great! However, I recommend another approach that integrates better with the framework provided by Spring security: provide a custom JWT auth converter.

The end goal of the converter would be to be used like this in the web security config:
```kotlin
@Configuration
@EnableWebSecurity
class WebSecurityConfig {

    @Autowired
    private lateinit var jwtAutoConverter: JwtAuthConverter

    @Bean
    fun securityFilterChain(http: HttpSecurity): SecurityFilterChain {
        // ...
        http.oauth2ResourceServer()
            .jwt()
            .jwtAuthenticationConverter(jwtAutoConverter)

        // ...
    }
}
```

The `JwtAuthConverter` class should look something like this:
```kotlin
@Component
class JwtAuthConverter : Converter<Jwt, AbstractAuthenticationToken> {

    override fun convert(jwt: Jwt): AbstractAuthenticationToken? {
        // ...
    }
}
```

Its main purpose is to take a `Jwt` as an input and convert it to an `AbstractAuthenticationToken`, which is the thing that Spring security uses to determine everything related to the identity and premisions of the current user. This can later be injected to access these details in the controller.

Let me know if you need more details on how you can implement this

2024-01-15 14:56 UTC, DrBaxR requested changes

2024-01-15 14:56 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/dto/PrizeDrawRequest.kt
I think it's better to have a single DTO class for each entity, that has nullable fields for the fields that are in the Response class but not in the Request class. So I would say combine `PrizeDrawRequest` and `PrizeDrawResponse` into `PrizeDrawDTO`.

Do the same thing for all other entities from this PR with a Request and Response class

2024-01-16 09:04 UTC, DanceaRadu commented on src/main/kotlin/ro/hibyte/betting/dto/PrizeDrawRequest.kt
[x]

2024-01-16 10:28 UTC, DrBaxR approved these changes

2024-01-16 14:05 UTC, AvrAlexandra approved these changes

2024-01-16 14:13 UTC, merged