Crud competitions v2#4
HibyteIntern/internal-betting-be pull request #21
Opened 2024-01-16 10:55 UTC by Serban681

Updated the api for competition related stuff #5

2024-01-16 14:39 UTC, DrBaxR requested changes

2024-01-16 14:39 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/config/WebSecurityConfig.kt
> +                    //.anyRequest().authenticated()
Revert to how it was before

2024-01-16 14:39 UTC, DrBaxR commented on src/main/kotlin/ro/hibyte/betting/controller/CompetitionController.kt
> +@RequestMapping("/api/v2/competitions")
No need to increase the version number yet, since the application didn't reach a production stage yet and there are no real clients that use it

2024-01-22 10:13 UTC, DanceaRadu approved these changes

2024-01-22 13:52 UTC, DrBaxR approved these changes

2024-01-22 14:40 UTC, merged